### ISSUE TITLE
Is IRIX 5.3 installation supported?

### ISSUE THREAD

**Issue by ThisIsWebGoat** [unxmaal/booterizer#27]
So far I have always used booterizer to install IRIX 6.5.22 on various Indigo2s, but now I tried to prepare everything to set up IRIX 5.3 on my R3k Iris Indigo, which does not support 6.x. 

When I change "irixversion" in settings.yml to "5.3" and run "ansible-playbook...." it fails at some point with error:
```
TASK fetch_files: Fetch overlay disc 1
fatal: [localhost] failed: the task includes an option with an unidentified variable. the error was: 'dict object' has no attribute 'Overlay'.
The error appears to be in '/root/projects/github/booterizer/ansible/roles/fetch_files/tasks/setup_media.yml' line 32, column 3, ... the offending line appears to be: name: Fetch overlay disc1
```

Now I am not sure whether IRIX 5.3 is really supported in booterizer (I'm using the raspi version)? Although I have seen references to 5.3 in some yml files, but in the github readme it seems to be 6.5.x only?

thanks!

**Comment by unxmaal** [comment]
Nope. See the README, Overview: "(See Callahan's Booterizer 5.3 https://github.com/callahan-44/booterizer )"
