### ISSUE TITLE
IRIX 6.5.22 disc2.tar.gz has additional CDROM prefix

### ISSUE THREAD

**Issue by vvuk** [unxmaal/booterizer#35]
the 6.5.22 overlay disc2 has an additional CDROM dir prefix:

```
vladimir@media:~/proj/booterizer/irix/6.5.22/Overlay/disc2$ tar tvzf disc2.tar.gz
drwxr-xr-x ftp/ftp           0 2018-05-12 02:31 disc2/
drwxr-xr-x ftp/ftp           0 2018-05-12 02:31 disc2/CDROM/
-rw-r--r-- ftp/ftp         197 2018-05-12 02:31 disc2/CDROM/.IM
-rw-r--r-- ftp/ftp        3218 2018-05-12 02:31 disc2/CDROM/CDrelnotes
drwxr-xr-x ftp/ftp           0 2018-05-12 02:31 disc2/CDROM/dist/
...
```

which means that it gets extracted as just 'CDROM' and then I think totally ignored during the install process.  Most everything on disc2 looks like it gets replaced by either devlibs or apps later on, but not all.  I noticed this because disc2 would always get re-extracted when I re-provisioned the vagrant VM.

IRIX 6.5.30 disc2 does _not_ have this extra CDROM path; probably not many folks installing 6.5.22 :)

**Comment by unxmaal** [comment]
This is a problem with that disc2.tar.gz. I'll bug Massive to fix it.

**Comment by unxmaal** [comment]
This is resolved.
