### ISSUE TITLE
booterizer pi image

### ISSUE THREAD

**Issue by paranoid64** [unxmaal/booterizer#36]
Hi, 

i have download the booterizer_6.5.30_1.1.071321.xz and works fine on Rasp Pi B.

Only the instructions would have to be adapted somewhat. E.g. it is no longer called eth0 with Buster, but e.g. with me enxb827eb33a83c:

root@booterizer:/home/pi# **ifconfig**
```
**enxb827eb33a83c**: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
        inet 192.168.1.1 netmask 255.255.255.0 broadcast 192.168.1.255
        inet6 2003:ee:719:f500:e788:62a7:9d32:3b91 prefixlen 64 scopeid 0x0<global>
```

I had to reconfigure a few things:

**/etc/dhcp/dhcpd.conf**

INTERFACES="enxb827eb33a83c";
allow booting;
allow bootp;

```
subnet 192.168.1.0 netmask 255.255.255.0 {
#       ignore unknown-clients;
        range 192.168.1.80 192.168.1.200; # **you need now this line, Service will not start otherwise**

        host sgi {
                hardware ethernet xx:xx:xx:xx:xx:xx; # you mac
                fixed-address 192.168.1.82 ;
                option domain-name-servers 192.168.1.1;
                option domain-name "iris.local";
        }
}
```

**nano /etc/default/isc-dhcp-server**
`INTERFACES="enxb827eb33a83c"`

 **nano /etc/dhcpcd.conf:**
```
interface enxb827eb33a83c
static ip_address=192.168.1.1/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1
```

**Comment by unxmaal** [comment]
I've fixed this on the latest Booterizer image. 

If you want to fix it the easy way on an existing install, run 'sudo raspi-config', choose "2 Network Options" from the main menu then "N3 Network interface names" from the sub-menu and that will enable predictable names on the next reboot.
