### ISSUE TITLE
Incorrect Overlay disc2 path for 6.5.22 

### ISSUE THREAD

**Issue by etbusch** [unxmaal/booterizer#43]
https://github.com/unxmaal/booterizer/blob/4bede34c5f30101204d2ce109fad6cbe616b9348/ansible/roles/fetch_files/templates/selections.j2#L3-L7

Using the prebuilt RPI image and images downloaded today the dist folder for Overlay disc2 is the same as 5.2.30: `/Overlay/disc2/dist`

This caused the installer to report many conflicts and missing subystems, and I had to manually include it in the installer.

I am not sure if this is the case for everyone, but it was for me.

**Comment by Docter60** [comment]
#45 should fix this

**Comment by etbusch** [comment]
Confirmed the fix. Thanks!
