### ISSUE TITLE
"Sending NAK (4, Request not null-terminated)" error (Indigo 2 R10K, 6.5.30)

### ISSUE THREAD

**Issue by dmitryelj** [unxmaal/booterizer#44]
Hi all, thanks for the cool project. 

I'm trying to use booterizer, running on a Raspberry Pi 4, to install IRIX 6.5.30 to the Indigo 2, and get 2 issues:

I. Indigo2 R10K is a 64bit CPU, so fx.64 command is required for this CPU instead of fx.ARCS, please fix the description

But anyway, the fx partitioner works, so the Ethernet connection between RPi4 and SGI is working.

II. But when I try to install the system, I get this error

```
Enter the name of the remote host: booterizer
Enter the remote directory: /6.5.30/Overlay/disc1/dist

Setting $netaddr to 192.0.2.82 (from server )
Unable to execute network(0)bootp()booterizer:/6.5.30/Overlay/disc1/dist/sa(sash64):  invalid argument
Cannot load network(0)bootp()booterizer:/6.5.30/Overlay/disc1/dist/sa(sash64) -- invalid argument.
```

At the same time, I can see this error in the booterizer log:

```
booterizer dhcpd[840]: BOOTREQUEST from 08:00:69:0a:a3:2b via eth0
booterizer dhcpd[840]: BOOTREPLY for 192.0.2.82 to sgi (08:00:69:0a:a3:2b) via eth0
booterizer in.tftpd[999]: RRQ from 192.0.2.82 filename /6.5.30/Overlay/disc1/stand/fx.64
booterizer dhcpd[840]: BOOTREQUEST from 08:00:69:0a:a3:2b via eth0
booterizer dhcpd[840]: BOOTREPLY for 192.0.2.82 to sgi (08:00:69:0a:a3:2b) via eth0
booterizer in.tftpd[1000]: RRQ from 192.0.2.82 filename /6.5.30/Overlay/disc1/dist/sa
booterizer in.tftpd[1000]: sending NAK (4, Request not null-terminated) to 192.0.2.82
```

For some reason, booterizer sending a correct response for the disc1/stand/fx.64 file but sending NAK for the disc1/dist/sa.
Any ideas, what can be wrong?

Thanks

**Comment by unxmaal** [comment]
Verify the files on-disk on the rPi. There's always a chance the image is misconfigured. 

Verify the configuration in settings.yml .

Re-run ansible-playbook:

cd /root/projects/github/booterizer/ansible
ansible-playbook -i inventory.yml rpi_booterizer.yml

then check the files at path /6.5.30/Overlay/disc1/dist/ again.

**Comment by dmitryelj** [comment]
Thanks for the answer. I've found that the "Request not null-terminated" error is generated by the tftpd itself, not by booterizer code. File /6.5.30/Overlay/disc1/dist/sa is present on RPi and has a proper size, so it looks more like error on the network/ethernet layer. So if there are no ideas what can be wrong, this ticket can be closed, I don't think there is an easy fix for that, it's looks easier to install IRIX from CD :)

**Comment by unxmaal** [comment]
Is your SGI connected directly via single ethernet cable to your rPi? If not, try that.

**Comment by dmitryelj** [comment]
Thanks for help again.

Yes, I use direct connection. A problem solved by entering the command _sudo ifconfig eth0 mtu 1200_ on the RPi before running install.
