### ISSUE TITLE
Minor issues when using RasPi image

### ISSUE THREAD

**Issue by RetroSwim** [unxmaal/booterizer#46]
I just deployed 6.5.22 to my Indigo2 successfully, using a Pi 3B, with just 2 minor hiccups:

- After running the ansible script, the resulting "selections" file in /irix has a typo. The Overlays 2 line read "from 192.0.2.99:6.5.22/Overlay/disc2/CDROM/dist", obviously the "CDROM/" part shouldn't be there.
- Raspbian seems to use so-called "predictable interface names" by default, so the wired ethernet interface is called "ethXXXXXXXXXX" where the X's are the MAC address. I needed to turn this off in raspi-config for the ansible script to succeed. I suspect it would have also worked if I had entered the "ethXXXXXXXXXX" interface name to the settings.yml in the 'bridgenic' line. One way or another the README could mention this maybe?

Image version is booterizer_6.5.30_1.1.112021.img

Otherwise this is an awesome project, thank you for putting in all the effort. Certainly made my life a heck of a lot easier! :)

**Comment by unxmaal** [comment]
The first was fixed a few months ago in the code. However, I haven't updated and pushed the image on booterizer.com .

For the second, feel free to submit a pull request with proposed changes.

Thanks!
